inputs:
  project:
    description: "Name of project to be tested"
    required: true
  install:
    description: "List of extra libraries or stubs to be installed"
    required: false
    default: ""
  ignore:
    description: "List of libraries to be ignored"
    required: false
    default: ""
  allow_untyped_defs:
    description: "Allow untyped defs"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - run: |
    
          RAPYDO_VERSION=$(grep "  rapydo:" projects/${{ inputs.project }}/project_configuration.yaml | sed 's/  rapydo: //' | tr -d '"')

          if [[ "${{ inputs.allow_untyped_defs }}" == "true" ]]; then
            DISALLOW_UNTYPED_DEFS="0"
          else
            DISALLOW_UNTYPED_DEFS="1"
          fi

          docker run --rm -i \
            -e PROJECT_NAME=${{ inputs.project }} \
            -e DISALLOW_UNTYPED_DEFS="${DISALLOW_UNTYPED_DEFS}" \
            -e IGNORE_LIBS="${{ inputs.ignore }}" \
            -e ADD_LIBS="${{ inputs.install }}" \
            -v $(pwd)/projects/${{ inputs.project }}/backend:/code/${{ inputs.project }} \
            -v $(pwd)/submodules/http-api/tests:/code/tests \
            -v $(pwd)/projects/${{ inputs.project }}/backend/tests:/code/tests/custom \
            rapydo/mypy:${RAPYDO_VERSION} bash

      shell: bash

