inputs:
  id:
    description: "Cypress Project ID"
    required: true
  key:
    description: "Cypress Project Key"
    required: true
  folder:
    description: "Optional folder from where extract COMMIT info"
    required: false
runs:
  using: "composite"
  steps:
    - run: |
          export CYPRESS_PROJECT_ID=${{ inputs.id }}
          export CYPRESS_RECORD_KEY=${{ inputs.key }}

          if [[ ! -z "${{ inputs.folder }}" ]]; then
            cd ${{ inputs.folder }};
          fi

          # Extra variables needed by Cypress
          export COMMIT_INFO_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          export COMMIT_INFO_MESSAGE="$(git show -s --pretty=%B)"
          export COMMIT_INFO_SUBJECT="$(git show -s --pretty=%s)"
          export COMMIT_INFO_BODY="$(git show -s --pretty=%b)"
          export COMMIT_INFO_EMAIL="$(git show -s --pretty=%ae)"
          export COMMIT_INFO_AUTHOR="$(git show -s --pretty=%an)"
          export COMMIT_INFO_SHA="$(git show -s --pretty=%H)"
          export COMMIT_INFO_TIMESTAMP="$(git show -s --pretty=%ct)"
          export COMMIT_INFO_REMOTE="$(git config --get remote.origin.url)"
          export CYPRESS_GROUP="$(git show -s --pretty=%H)"

          # Make the environment variables available to next the steps

          echo "CYPRESS_PROJECT_ID=${CYPRESS_PROJECT_ID}" >> $GITHUB_ENV
          echo "CYPRESS_RECORD_KEY=${CYPRESS_RECORD_KEY}" >> $GITHUB_ENV

          # Extra variables needed by Cypress
          echo "COMMIT_INFO_BRANCH=${COMMIT_INFO_BRANCH}" >> $GITHUB_ENV
          echo "COMMIT_INFO_MESSAGE=${COMMIT_INFO_MESSAGE}" >> $GITHUB_ENV
          echo "COMMIT_INFO_SUBJECT=${COMMIT_INFO_SUBJECT}" >> $GITHUB_ENV
          echo "COMMIT_INFO_BODY=${COMMIT_INFO_BODY}" >> $GITHUB_ENV
          echo "COMMIT_INFO_EMAIL=${COMMIT_INFO_EMAIL}" >> $GITHUB_ENV
          echo "COMMIT_INFO_AUTHOR=${COMMIT_INFO_AUTHOR}" >> $GITHUB_ENV
          echo "COMMIT_INFO_SHA=${COMMIT_INFO_SHA}" >> $GITHUB_ENV
          echo "COMMIT_INFO_TIMESTAMP=${COMMIT_INFO_TIMESTAMP}" >> $GITHUB_ENV
          echo "COMMIT_INFO_REMOTE=${COMMIT_INFO_REMOTE}" >> $GITHUB_ENV
          echo "CYPRESS_GROUP=${CYPRESS_GROUP}" >> $GITHUB_ENV
          echo "Cypress environment is ready"

          if [[ ! -z "${{ inputs.folder }}" ]]; then
            cd -;
          fi

      shell: bash
