inputs:
  project:
    description: "Name of the RAPyDo Project to be configured"
  codecov_token:
    description: "Codecov Token"
    required: false
runs:
  using: "composite"
  steps:
    - run: |
          python -m pip install --upgrade pip
          export RAPYDO_VERSION=$(grep "  rapydo:" projects/${{ inputs.project}}/project_configuration.yaml | sed 's/  rapydo: //' | tr -d '"')
          # Make the environment variable available to next steps
          echo "RAPYDO_VERSION=${RAPYDO_VERSION}" >> $GITHUB_ENV
          echo "CODECOV_TOKEN=${{ inputs.codecov_token }}" >> $GITHUB_ENV
          pip install --upgrade --no-cache-dir git+https://github.com/rapydo/do.git@${RAPYDO_VERSION}
          rapydo --testing --project ${{ inputs.project}} init
          rapydo version
      shell: bash
    # - run: echo "Nice to meet you!"
    #   shell: pwsh
