inputs:
  project:
    description: "Name of the RAPyDo Project to be configured"
  submodule:
    description: "RAPyDo submodule do be installed"
    required: false
    default: "do"
  swarm:
    description: "Enable Swarm Mode"
    required: false
    default: 0
runs:
  using: "composite"
  steps:
    - run: |

          if [[ "${{ inputs.swarm }}" == "1" ]]; then
            export SWARM_MODE=1
            echo "SWARM_MODE=1" >> $GITHUB_ENV
          fi

          python -m pip install --upgrade pip wheel
          export RAPYDO_VERSION=$(grep "  rapydo:" projects/${{ inputs.project }}/project_configuration.yaml | sed 's/  rapydo: //' | tr -d '"')
          # Make the environment variable available to next steps
          echo "RAPYDO_VERSION=${RAPYDO_VERSION}" >> $GITHUB_ENV
          pip install --upgrade --no-cache-dir git+https://github.com/rapydo/${{ inputs.submodule }}.git@${RAPYDO_VERSION}
                  
          if [[ "${{ inputs.submodule }}" == "do" ]]; then

            rapydo install buildx
            rapydo install compose

            rapydo --testing --project ${{ inputs.project }} init
            
            if [[ "${{ inputs.swarm }}" == "1" ]]; then

              IP_DEV=$(python3 -c "from controller.utilities import system; print(system.get_local_ip(production=False))")
              IP_PROD=$(python3 -c "from controller.utilities import system; print(system.get_local_ip(production=True))")
              sudo cat /etc/docker/daemon.json
              sudo bash -c "echo '{\"cgroup-parent\": \"/actions_job\", \"insecure-registries\" : [\"127.0.0.1:5000\", \"${IP_DEV}:5000\", \"${IP_PROD}:5000\"]}' >  /etc/docker/daemon.json"
              sudo cat /etc/docker/daemon.json
              sudo systemctl restart docker.service

              rapydo run --pull registry
              sleep 3
            fi

            rapydo version

          fi
      shell: bash
